### ISSUE TITLE
Expand permissions for dataflow

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/data-and-compute-team#10]
Currently only I can monitor the Google console and check on how dataflow jobs are doing. That is not a great situation. 

- [x] We should add other members with dataflow admin rights to the project - Closed via https://github.com/leap-stc/leap-stc.github.io/pull/167
- [x] I would like to enable users to click on the dataflow links and see the graph, progress etc, but not have access to modify anything for security reasons. I am not sure how to achieve this, but will investigate.

**Comment by norlandrhagen** [comment]
Looking at the dataflow console I see this permission error:
```
Troubleshooting info:
  Principal: raphael@carbonplan.org
  Resource: leap-pangeo
  Troubleshooting URL: console.cloud.google.com/iam-admin/troubleshooter;permissions=dataflow.jobs.get;principal=raphael@carbonplan.org;resources=%2F%2Fcloudresourcemanager.googleapis.com%2Fprojects%2Fleap-pangeo/result

Missing permissions:
  dataflow.jobs.get
  ```
  
  Maybe we just need add`  dataflow.jobs.get` to our profiles? I'm not really familiar with gcp.

**Comment by norlandrhagen** [comment]
cc @jbusecke it would be nice to get dataflow console permissions and bucket rw permissions to google storage for the pangeo-forge-leap related buckets.
