### ISSUE TITLE
Add (some) members to Google Dataflow alerts

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/data-and-compute-team#17]
It would be useful to have more eyes on potentially expensive long running data flow jobs. Are folks who have DF access ok with getting pinged by email? @SammyAgrawal @norlandrhagen ?

**Comment by norlandrhagen** [comment]
I don't mind. Is there any sort of slack integration?

**Comment by jbusecke** [comment]
Not sure. I usually receive email alerts ( I set it up to be any job over 40k vcpu hours).

**Comment by jbusecke** [comment]
Ok I added you to my two dataflow alerts and the 2i2c disk space alert just for some redundancy.
